version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: dbseekjavachallenge
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
